apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      # - ./infra/k8s/core/*
      # - ./infra/k8s/auth/*
      # - ./infra/k8s/tickets/*
      - ./infra/k8s/orders/*
build:
  local:
    push: false
  artifacts:
    # - image: madhurachanna/auth
    #   context: auth
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.py'
    #         dest: .
    # - image: madhurachanna/tickets
    #   context: tickets
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.py'
    #         dest: .
    - image: madhurachanna/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.py'
            dest: .