apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-redis
  template:
    metadata:
      labels:
        app: tickets-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379


---
apiVersion: v1
kind: Service
metadata:
  name: tickets-redis-service
spec:
  type: ClusterIP
  selector:
    app: tickets-redis
  ports:
    - port: 6379
      targetPort: 6379

