apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-postgres
  template:
    metadata:
      labels:
        app: tickets-postgres
    spec:
      containers:
        - name: tickets-postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tickets-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: tickets-secret
                  key: POSTGRES_DB 
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tickets-secret
                  key: POSTGRES_PASSWORD 
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: tickets-postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: tickets-postgres-storage
          persistentVolumeClaim:
            claimName: tickets-db-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: tickets-postgres-service
spec:
  type: ClusterIP
  selector:
    app: tickets-postgres
  ports:
    - port: 5432
      targetPort: 5432


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tickets-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi