apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: madhurachanna/orders
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: POSTGRES_USER 
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: POSTGRES_DB 
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: POSTGRES_HOST
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: JWT_KEY        
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_DEFAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_HOST
            - name: RABBITMQ_DEFAULT_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PORT
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_VHOST

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000