apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: madhurachanna/auth
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-auth-data
                  key: USER 
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pg-auth-data
                  key: DB 
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-auth-data
                  key: PASS 

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  # type: ClusterIP
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000